[gauntlet]
name = 'Dictionary'
description = """
Search for meanings of words
"""

[[entrypoint]]
id = 'search'
name = 'Dictionary search'
path = 'src/dict-search.tsx'
type = 'view'
icon = 'extension_icon.png'
description = """
Find the meaning of a word
"""

[permissions]
network = ["api.datamuse.com"]