[gauntlet]
name = 'Dictionary'
description = """
Search for meanings of words
"""

[[entrypoint]]
id = 'search'
name = 'Dictionary search'
path = 'src/dict-search.tsx'
type = 'view'
icon = 'extension_icon.png'
description = """
Find the meaning of a word
"""

[permissions]
network = ["api.datamuse.com", "freedictionaryapi.com"]
clipboard = ["write"]

[permissions.exec]
command = ["xdg-open", "open", "start", "firefox"]

[[supported_system]]
os = 'linux'